// Checks that the atlas map still behaves: drag, click, keyboard, deep links, zoom.
// Usage (from scripts/browser): node atlas-test.mjs   (exits 1 on failure)
import { launch, serve } from "./site.mjs";

const browser = await launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const page = await ctx.newPage();
const errs = [];
page.on("pageerror", (e) => errs.push(e.message));
page.on("console", (m) => m.type() === "error" && errs.push(m.text()));
await serve(page);
await page.goto("http://site.test/atlas", { waitUntil: "networkidle" });
const vb = () => page.$eval("#atlas-svg", (s) => s.getAttribute("viewBox"));
let failed = 0;
const ok = (name, cond) => { if (!cond) failed++; console.log((cond ? "✓ " : "✗ ") + name); };
const v0 = await vb();
await page.mouse.move(900, 500); await page.mouse.down(); await page.mouse.move(800, 450, { steps: 5 }); await page.mouse.up();
await page.waitForTimeout(100);
ok("drag pans the map", (await vb()) !== v0);
ok("drag does not open a panel", await page.$eval("#atlas-panel", (p) => p.hidden));
const box = await page.locator('[data-place="goodmorrow"] text').boundingBox();
await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2);
await page.waitForTimeout(900);
ok("click opens panel", !(await page.$eval("#atlas-panel", (p) => p.hidden)));
ok("panel title is Goodmorrow", (await page.textContent(".panel-title")) === "Goodmorrow");
ok("hash is #goodmorrow", (await page.evaluate(() => location.hash)) === "#goodmorrow");
await page.keyboard.press("Escape");
ok("escape closes", await page.$eval("#atlas-panel", (p) => p.hidden));
ok("hash cleared", (await page.evaluate(() => location.hash)) === "");
await page.click('[data-show="the-unrun"]');
await page.waitForTimeout(1200);
ok("gazetteer button opens The Unrun", (await page.textContent(".panel-title")) === "The Unrun");
ok("scrolled back to map", (await page.evaluate(() => window.scrollY)) < 120);
const z0 = await vb();
await page.mouse.move(700, 450);
await page.keyboard.down("Control"); await page.mouse.wheel(0, -200); await page.keyboard.up("Control");
await page.waitForTimeout(100);
const w = (s) => Number(s.split(" ")[2]);
ok("ctrl+wheel zooms in", w(await vb()) < w(z0));
const sy = await page.evaluate(() => window.scrollY);
await page.mouse.wheel(0, 300); await page.waitForTimeout(300);
ok("plain wheel scrolls the page", (await page.evaluate(() => window.scrollY)) > sy);
await page.evaluate(() => window.scrollTo(0, 0));
await page.focus("#atlas-viewport");
const k0 = await vb(); await page.keyboard.press("ArrowRight"); await page.waitForTimeout(80);
ok("arrow key pans", (await vb()) !== k0);
await page.click('[data-act="home"]');
await page.focus("#atlas-viewport");
await page.keyboard.press("Tab");
const focused = await page.evaluate(() => document.activeElement?.dataset?.place);
ok("tab reaches a place: " + focused, !!focused);
await page.keyboard.press("Enter"); await page.waitForTimeout(900);
ok("enter opens it", (await page.textContent(".panel-title")).length > 0 && !(await page.$eval("#atlas-panel", (p) => p.hidden)));
await page.click('[data-act="home"]'); await page.waitForTimeout(900);
ok("home closes panel", await page.$eval("#atlas-panel", (p) => p.hidden));
await page.goto("http://site.test/atlas#cape-almost", { waitUntil: "networkidle" }); await page.waitForTimeout(1200);
ok("deep link opens Cape Almost", (await page.textContent(".panel-title")) === "Cape Almost");
ok("no errors: " + errs.join(" | "), errs.length === 0);
await browser.close();
process.exit(failed ? 1 : 0);
